In [52]:
# TODO: ao apresentar apenas tabelas de output codes com a máxima menor distância, filtrar também para apresentar só as com maior média de distância de Hamming entre seus pares
import numpy as np
from scipy.spatial.distance import pdist, squareform

numclasses = 7
numbits = 14
lim_min_dist = 0

"""
classe, bits, dmin, quant
2, 2, 2, 1
2, 3, 3, 1
2, 4, 4, 1
2, 5, 5, 1

3, 2, 1, 3
3, 3, 2, 3

4, 2, 1, 1
4, 3, 2, 1
4, 4, 2, 44
4, 5, 2, 420
4, 6, 3, 840
4, 7, 4, 840

5, 3, 1, 35
5, 4, 2, 40
5, 5, 2, 3565
5, 6, 3, 3150
5, 7, 4,
        2333012 [[1 1 1 1 1 1 1]
         [0 0 0 0 0 0 1]
         [0 0 0 1 1 1 0]
         [0 1 1 0 0 1 0]
         [1 0 1 0 1 0 0]]
5, 8, 4, 82
5, 9, 4, 1290
5, 10, 5, 1
5, 11, 6, 15
5, 12, 6, 172
5, 13, 6, 455
5, 14, 7, 455
5, 15, 8
"""

qbits = (2**(numclasses-1)) - 1
ecoc_matrix = ([np.ones(qbits)])
for i in range(1, numclasses):
    code = np.zeros(qbits)
    tbits = int((qbits + 1) / (2**i))
    for j in range(tbits, qbits, tbits*2):
        code[j:j+tbits] = 1
    ecoc_matrix.append(code)

solucoes = []
ecoc_exaustivo = np.array(ecoc_matrix).astype(int)
ecoc_matrix = ecoc_exaustivo
distances = pdist(ecoc_matrix, metric='hamming') * ecoc_matrix.shape[1]
min_dist = int(np.min(distances))
print(f"{ecoc_matrix.shape[0]}, {ecoc_matrix.shape[1]}, {min_dist}")


#print(j, i, ecoc_exaustivo)
qbitsf = numbits
for r in range(0, qbitsf):
    ecoc_matrix7 = np.delete(ecoc_exaustivo, r, axis=1) if numbits <= 8 else ecoc_exaustivo
    for b in range(r, qbitsf):
        ecoc_matrix6 = np.delete(ecoc_matrix7, b, axis=1) if numbits <= 9 else ecoc_exaustivo
        for v in range(b, qbitsf):
            ecoc_matrix5 = np.delete(ecoc_matrix6, v, axis=1) if numbits <= 10 else ecoc_exaustivo
            for m in range(v, qbitsf):
                ecoc_matrix4 = np.delete(ecoc_matrix5, m, axis=1) if numbits <= 11 else ecoc_exaustivo
                for k in range(m, qbitsf):
                    ecoc_matrix3 = np.delete(ecoc_matrix4, k, axis=1) if numbits <= 12 else ecoc_exaustivo
                    for j in range(k, qbitsf):
                        ecoc_matrix2 = np.delete(ecoc_matrix3, j, axis=1) if numbits <= 13 else ecoc_exaustivo
                        for i in range(j, qbitsf):
                            ecoc_matrix = np.delete(ecoc_matrix2, i, axis=1)  if numbits <= 14 else ecoc_exaustivo
                            # Calcula a matriz de distâncias de Hamming
                            distances = pdist(ecoc_matrix, metric='hamming') * ecoc_matrix.shape[1]
                            min_dist = int(np.min(distances))
                            if(min_dist < lim_min_dist):
                                continue
                            if min_dist > lim_min_dist:
                                lim_min_dist = min_dist
                                solucoes = []
                                print(f"{i} {min_dist}")
                                print(r, b, m, k, k, j, i, ecoc_matrix)
                                
                            solucoes.append(i)
    
#for i in solucoes:
    #print(f"seed = {i}")

print(f"{ecoc_matrix.shape[0]}, {ecoc_matrix.shape[1]}, {lim_min_dist}, {len(solucoes)}")


7, 63, 32
0 31
0 0 0 0 0 0 0 [[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0
  0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1]
 [0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1
  1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1]
 [0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0
  0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
  1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]]
7, 62, 31, 77520


In [118]:
k


0

In [ ]:

if False:
    
    def gen_ecoc_matriz(seed):
        sseed = seed
        filtro = (2 ** numbits) - 1
        lastval = seed & filtro
        for j in range(numclasses-2):
            sseed = (sseed >> numbits) 
            val = sseed & filtro
            if val >= lastval:
                return None
            lastval = val
    
        bits = np.array(list(f"{seed:064b}"), dtype=int)
        ecoc_matrix = ([np.ones(numbits)])
        ini = 64 - (numclasses-1) * numbits
        for j in range(numclasses-1):
            ecoc_matrix.append(bits[ini:ini + numbits])
            ini += numbits
        ecoc_matrix = np.array(ecoc_matrix).astype(int)
        for j in range(numbits):
            if np.sum(ecoc_matrix[:,j]) == numclasses: #coluna toda de zeros ou 1!
                return None
        for j in range(numbits-1):
            for i in range(j+1, numbits):
                if np.all(ecoc_matrix[:,j] == ecoc_matrix[:,i]):
                    return None
        return ecoc_matrix
    
    solucoes = []
    quant = (2**numbits) ** (numclasses-1)
    for i in range(quant):
    #for i in range(128*128-1,128*128+10):
        if i % 1000000 == 0:
            print(i, ":")
        ecoc_matrix = gen_ecoc_matriz(i)
        if ecoc_matrix is None:
            continue
        # Calcula a matriz de distâncias de Hamming
        distances = pdist(ecoc_matrix, metric='hamming') * ecoc_matrix.shape[1]
        min_dist = int(np.min(distances))
        if(min_dist < lim_min_dist):
            #print(f"{i} {min_dist}")
            #print(i, ecoc_matrix)
            continue
    
        if(min_dist > lim_min_dist):
            lim_min_dist = min_dist
            print(f"{i} {min_dist}")
            print(i, ecoc_matrix)
            solucoes = []
        
        solucoes.append(i)
    
    #for i in solucoes:
    #    print(f"seed = {i} {gen_ecoc_matriz(i)}")
    
    print(f"{numclasses}, {numbits}, {lim_min_dist}, {len(solucoes)}")
            
